In [1]:
import os
import torch

os.getcwd()

'/home/rasmus.thrane/Thesis/GraphMVP'

In [ ]:
path_to_data = "./datasets/molecule_datasets/malaria/processed/geometric_data_processed.pt"

data = torch.load(path_to_data)
print(data[0])
# outputs (Data(edge_attr=[10770, 2], edge_index=[2, 10770], id=[642], x=[5600, 2], y=[642]),

None


In [40]:
data

(Data(edge_attr=[10770, 2], edge_index=[2, 10770], id=[642], x=[5600, 2], y=[642]),
 {'x': tensor([   0,   13,   18,   23,   31,   39,   48,   54,   61,   69,   74,   77,
            84,   92,  101,  108,  119,  128,  137,  145,  152,  162,  181,  189,
           196,  204,  210,  215,  223,  227,  232,  240,  245,  263,  274,  279,
           290,  298,  309,  316,  325,  330,  339,  350,  359,  371,  378,  387,
           391,  398,  405,  410,  416,  424,  435,  439,  449,  451,  458,  471,
           487,  496,  497,  511,  522,  533,  537,  552,  556,  560,  568,  576,
           596,  603,  612,  619,  622,  629,  643,  647,  656,  668,  677,  685,
           694,  698,  700,  705,  712,  719,  724,  742,  756,  759,  772,  776,
           780,  789,  793,  800,  820,  824,  831,  838,  841,  854,  864,  870,
           878,  883,  896,  907,  911,  919,  935,  943,  953,  958,  965,  974,
           992, 1001, 1015, 1018, 1027, 1035, 1041, 1055, 1057, 1070, 1074, 1079,
         

In [38]:
print(torch.unique(data[0].edge_index[0,:]))
print(torch.unique(data[0].edge_index[1,:]))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [31]:
print(torch.unique(data[0].x[:, 0]))  # Unique values in first column
print(torch.unique(data[0].x[:, 1]))  # Unique values in second column


tensor([ 5,  6,  7,  8, 14, 15, 16, 34, 52])
tensor([0, 1, 2])
