In [1]:
import os
import torch

os.getcwd()

'/home/rasmus.thrane/Thesis/GraphMVP'

In [5]:
path_to_data = "/home/rasmus.thrane/Thesis/GraphMVP/datasets/GEOM/GEOM_3D_nmol10_nconf5_nupper1000_morefeat/processed/geometric_data_processed.pt"

data = torch.load(path_to_data)
# outputs (Data(edge_attr=[10770, 2], edge_index=[2, 10770], id=[642], x=[5600, 2], y=[642]),

In [7]:
data[0]

RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.

In [38]:
print(torch.unique(data[0].edge_index[0,:]))
print(torch.unique(data[0].edge_index[1,:]))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [31]:
print(torch.unique(data[0].x[:, 0]))  # Unique values in first column
print(torch.unique(data[0].x[:, 1]))  # Unique values in second column


tensor([ 5,  6,  7,  8, 14, 15, 16, 34, 52])
tensor([0, 1, 2])
